name: usdc_wallet
description: "USDC Wallet - Mobile wallet app for sending and receiving USDC on Base Network. Built with Flutter for white-label Wallet as a Service project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  qr_flutter: ^4.1.0
  provider: ^6.1.1
  web3dart: ^2.7.3
  http: ^1.1.0
  crypto: ^3.0.3
  bip39: ^1.0.6
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^3.5.7
  flutter_local_notifications: ^17.2.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
